version: "3"
services:
    game-engine:
        image: bomberland:011a277
        volumes:
            - type: "bind"
              source: ./agents/replay.json
              target: /app/replay.json
        command: ./bomberland-engine

    python3-gym-dev:
        build:
            context: agents/python3
            dockerfile: Dockerfile
        volumes:
            - ./agents/python3:/app