version: "3"
services:
    gym:
        extends:
            file: base-compose.yml
            service: python3-gym-dev
        environment:
            - FWD_MODEL_CONNECTION_STRING=ws://fwd-server:6969/?role=admin
            - WANDB_API_KEY=b4f00a2d5dbba0577c580a658bc5028981a86ebf
        depends_on:
            - fwd-server
        networks:
            - coderone-open-ai-gym-wrapper

    fwd-server:
        extends:
            file: base-compose.yml
            service: game-engine
        environment:
            ADMIN_ROLE_ENABLED: "1"
            TRAINING_MODE_ENABLED: "1"  # 明确设置
            TELEMETRY_ENABLED: "0"
            PORT: "6969"
            WORLD_SEED: "1234"
            PRNG_SEED: "1234"
        networks:
            - coderone-open-ai-gym-wrapper

networks:
    coderone-open-ai-gym-wrapper: null
