wandb_version: 1

action_dim:
  desc: null
  value: 7
benchmark_batch_size:
  desc: null
  value: 20
checkpoint_dir:
  desc: null
  value: checkpoints
clip_eps:
  desc: null
  value: 0.2
device:
  desc: null
  value: cpu
eval_frequency:
  desc: null
  value: 100
fwd_model_uri:
  desc: null
  value: ws://fwd-server:6969/?role=admin
gamma:
  desc: null
  value: 0.99
keep_last_n_checkpoint:
  desc: null
  value: 100
lam:
  desc: null
  value: 0.95
log_frequency:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.0003
map_channels:
  desc: null
  value: 8
map_size:
  desc: null
  value: 15
max_steps_per_episode:
  desc: null
  value: 650
num_envs:
  desc: null
  value: 5
num_episodes:
  desc: null
  value: 10000
num_units:
  desc: null
  value: 3
save_frequency:
  desc: null
  value: 50
self_state_dim:
  desc: null
  value: 10
sequence_length:
  desc: null
  value: 20
update_target_frequency:
  desc: null
  value: 15
_wandb:
  desc: null
  value:
    python_version: 3.8.20
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745977320.852676
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.20
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
